apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # Papel de uma service account
metadata:
  name: server-read
rules: # Regras
- apiGroups: [""] # Recursos baseado na api que esta trabalhando
  resources: ["pods","services"] # Recursos que o usuario pode trabalhar
  verbs: ["get","watch","list"] # Acoes que ele pode utilizar
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list"]  
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # Bind que vai atribuir a role na service account de nome server
metadata:
  name: server-read-bind
subjects:
- kind: ServiceAccount
  name: server
  namespace: prod
roleRef:
  kind: ClusterRole
  name: server-read
  apiGroup: rbac.authorization.k8s.io