apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 50Gi # Capacidade do storage
  accessModes:
    - ReadWriteOnce # Pode gravar, ler, desde que voce esteja no mesmo node
    - ReadWriteMany