apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 10
  template:  # template do pod a ser replicado
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "luique97/hello-go:latest"
    